### PR TITLE
#24 resolved - Now pressing back key while shield discovery cancels the discovery process and #26 resolved - confirmation is asked before the shield is disconnected

### PR DESCRIPTION
**Pull request by rishabhjain08**
Added a cancel listener and checked if adapter was searching for shields, if yes then I cancelled the shield discovery. Solves issue #24.

### CODE REVIEW

**Comment by rishabhjain08** [comment]
issue #26 and issue #24 are related. They solve the problem together. Sending another pull request which will solve issue #26 as well.

**Comment by rishabhjain08** [comment]
#26 solved but an issue remains that even if there were no shields connected app will ask for confirmation to disconnect shield. Please make it a new issue if you accept this pull.

**Comment by ijdoc** [comment]
Any idea why this cannot be merged automatically?

**Comment by rishabhjain08** [comment]
Maybe because working with issue #38 required some changes in the same function i.e onSharedPrefChangedListener(). Should I can create a branch of that node make changes to it and then recommit.

**Comment by ijdoc** [comment]
If it is not too much trouble, it is worth trying. It is always easier to solve and merge fixes for issues separately.

**Comment by rishabhjain08** [comment]
Merged with pull request 48 to incorporate solution to issue #38.

**Comment by rishabhjain08** [comment]
Merged with pull request #48 so that this pull request contains the solution to issue number #38 also and so that the conflicts are resolved.

**Comment by ijdoc** [comment]
@rishabhjain08 testing for more than one issue for a single pull request makes things difficult to merge, please don't add any more commits to this request.

**Comment by rishabhjain08** [comment]
@jorgesilva ok

**Comment by rishabhjain08** [comment]
Seperating this request into 3 different pull requests. Closing this request.

**Pull request closed without merging**
