### PR TITLE
Left and right swipes change the direction of motion of the highlighter ...

### PR DESCRIPTION
**Pull request by rishabhjain08**
...with an option to turn this feature on and off (Solves issue #38)

### CODE REVIEW

**Comment by rishabhjain08** [comment]
I have added an option in the preference menu to turn the recognize gestures feature on or off. In this commit all the gestures are interpreted as either left or right swipes. By swiping to the left highlighter moves to the left and on swiping to the right highlighter moves to the right. When the keyboards are switched the scan direction is always set to HIGHLIGHT_NEXT initially. Solves issue #38

**Comment by rishabhjain08** [comment]
I have updated the name and summary for the option (recognize swipes) as suggested.

**Comment by ijdoc** [comment]
Can you please also update the name of the string in the file so it is closer to the actual name of the preference?

**Comment by rishabhjain08** [comment]
Renamed the variables to be more specific.
And made the preference depend on persistent keyboard and full screen switch.

**Comment by rishabhjain08** [comment]
Merged this solution of issue 38 (pull request 48) with the solution of issue 24 and 26 (pull request #56). Closing this pull request.

**Pull request closed without merging**
