### PR TITLE
Red Highlight Colour Pref. Fixes #171

### LINKED ISSUE #171: Make highlight colour a preference
With the change of the Tecla highlight from red to blue, some users may prefer to switch back to red since they may already be used to it

### PR DESCRIPTION
**Pull request by sagar-chandarana**
- Necessary layout-xmls and pngs added.
- Pref entry in layout and in the class Persistence

Additional Issues
- Need to translate added strings in es,fr and nl
- Keyboard layout (and colour) loaded during startup. So after changing
  the colour in prefs, need to restart the app to apply changes. Already working on this one.

### CODE REVIEW

**Comment by ijdoc** [comment]
It should not be necessary to define a second input xml file. Instead, the key background should be assigned programmatically after the keyboard is loaded. That will also allow for immediate change of the preference (rather than havingvto restart the app).

**Comment by sagar-chandarana** [comment]
I googled a lot, if I could assign key background AFTER the keyboard is loaded. But, the thing is background has to be loaded when the keyboard is created. And this background is reused everytime the keyboard is shown on the screen, that's why colour doesn't change immediately. One easy solution at the moment is, as all the blogs suggest, to force-redraw the keyboard when the colour is changed in prefs. The colour change will be applied immediately then. Creating extra xmls is necessary for this.

Although I am searching what better can be done.

**Comment by sagar-chandarana** [comment]
After 5 6 hours of researching, this is what I've been able to conclude:
-> The first thing which is called when IME starts: onCreateInputView(), where the layout and the background of keyboard is inflated and is used for the whole lifecycle.
-> To change this inflated background, we have to instantiate a new instance of TeclaKeyboardView and them pass them again to all the Contexts where it's used. I.e. Virtually restarting the app, not whole of it but a part of it.
-> I've tried different keyboards in the market which support themes (different colors and bgs). All of them redraws keyboard when theme is changed. I even tried to look at the source code of an open source IME, it too works this way. It's the Android which doesn't let us change the key-background on the go.

Please let me know if I should be working further on this issue.

**Comment by ijdoc** [comment]
Redrawing the keyboard is acceptable, is the method you will use to redraw called "invalidateKeyboard()" or something similar?

The other thing we need to consider is that the preference should be prepared to take more colours in the future (if needed). I would be willing to merge this as a branch while we finalize the user experience for the feature. Is it possible at all to create a composite that allows _any_ colour to be set?

**Comment by ijdoc** [comment]
This feature has been deprecated for this project in favour of implementing it for Tecla Access for Jelly Bean. See: https://github.com/idrc/tecla-as/issues/45

Therefore, this request is now invalid and will be closed.

**Pull request closed without merging**
